### ISSUE TITLE
Add ISO_1 to  exception in CharSet check

### ISSUE THREAD

**Issue by x1aoj1ang** [sqlanywhere/sqlanydb#14]
according to [SQL Anywhere 12.0.1 > SQL Anywhere Server - Database Administration > Database configuration > International languages and character sets > Locales](http://infocenter.sybase.com/help/topic/com.sybase.help.sqlanywhere.12.0.1/dbadmin/determining-locale-natlang.html),there is  a default charset  iso_1 , and it is **not** in the codecs .so it will cause error in the charset check.
```text
/opt/conda/lib/python3.6/site-packages/sqlanydb.py in __init__(self, args, kwargs, parent)
    572                 if isinstance(char_set, bytes):
    573                     char_set = char_set.decode()
--> 574                 if codecs.lookup(char_set):
    575                     self.valueof = mk_valueof((A_BINARY,), char_set)
    576                     self.assign = mk_assign(char_set)

LookupError: unknown encoding: iso_1
```
Thanks

**Comment by gperrow-SAP** [comment]
This shouldn't be necessary. Can you give me a sample script where the current driver does the wrong thing?

**Comment by gperrow-SAP** [comment]
I was unable to reproduce the original problem, but pull request #15 should fix it.
