### ISSUE TITLE
respect the charset config in connect config

### ISSUE THREAD

**Issue by x1aoj1ang** [sqlanywhere/sqlanydb#16]
the charset config(pass by user) in connect  should hava higher priority than other

**Comment by gperrow-SAP** [comment]
Fixed with pull request #15

**Comment by gperrow-SAP** [comment]
After looking at this again, I have reverted this change. We retrieve the character set of the connection and base the binary conversion on that rather than the one requested. They will usually be the same but if they differ, we must use the character set that the connection is actually using.
