### ISSUE TITLE
dbcapi.dll for old versions of SQL Anywhere

### ISSUE THREAD

**Issue by dcsoft4** [sqlanywhere/sqlanydb#17]
Hello, I am writing a client that connects to a SQL Anywhere 9 server (which comes with dblib9.dll).  But SQL Anywhere 9 does not come with dbcapi.dll.  Is there a way I can get the required dbcapi.dll which works with dblib9?  The earliest version of SQL Anywhere that I have found that comes with dbcapi.dll is SQL Anywhere 12.  

In general, does sqlanydb support connecting to multiple versions of the server?

Thanks,
David

**Comment by gperrow-SAP** [comment]
There is no version of dbcapi for SQLA version 9 - dbcapi did not exist then. But in answer to your second question, any version of the client that is newer than version 9 can connect to a version 9 server.

**Comment by dcsoft4** [comment]
Perhaps I am missing something.  When I use the dbcapi.dll from SQL Anywhere 17 and run my Python script, I get a messagebox saying: "The program can't start because dblib17.dll is missing from your computer. Try reinstalling the program to fix this problem."  

Looking at dbcapi.dll in a text viewer, I see the string "dblib17.dll", so it seems the dbcapi.dll coming with each version of SQL Anywhere is hard-coded to work with the equivalent dblibxx.dll (where xx is the version of SQL Anywhere)?

Ideally I would like the dbcapi.dll to work with dblib9.dll, dblib17.dll, and in general, any dblibXX.dll.  Is this possible?  Thanks again.

**Comment by gperrow-SAP** [comment]
Sorry, my answer was brief and unclear. Each dbcapi.dll is built to use a specific major version of dblibX.dll. When I talk about "the client" I mean dbcapi.dll, dblibX.dll and other supporting files (dbrsaX.dll, dblgenX.dll and possibly others). So the python driver loads dbcapi, dbcapi loads dblib, and dblib makes the connection to the server.

If you have a SQL Anywhere 9 server running, you can use any version of these files with your python script to connect to that server. The version of dblib and dbcapi have to match each other, but they don't have to match the version of the SQL Anywhere server they are connecting to.

**Comment by dcsoft4** [comment]
Ah!  That works, thank you!  I was confused because I am connecting to a server provided by a third party, who had redistributed dblib9.dll.  I thought my client would only need to provide the missing dbcapi.dll, and it would hook up with the dblib9.dll.  But installing all the DLL's from version 17 does connect to the version 9 server.

BTW, do you know if I need to obtain a license to redistribute these client DLL's (so I can access third party servers like this)?  All the licenses I see in the SAP store assume I want to buy some sort of server and I can't find a way to license the client so I can redistribute just these client DLL's (and not things like the Sybase Central GUI utility that also comes bundled with it.  I downloaded the client from https://wiki.scn.sap.com/wiki/display/SQLANY/SAP+SQL+Anywhere+Database+Client+Download.  Thanks so much.

**Comment by dcsoft4** [comment]
Ah!  That works, thank you!  I was confused because I am connecting to a server provided by a third party, who had redistributed dblib9.dll.  I thought my client would only need to provide the missing dbcapi.dll, and it would hook up with the dblib9.dll.  But I now provide all the DLL's you mention from SQL 12 Anywhere Client (downloaded from  https://wiki.scn.sap.com/wiki/display/SQLANY/SAP+SQL+Anywhere+Database+Client+Download), and now my code connects to the version 9 server.  :-)

BTW, do you know if I need to obtain a license to redistribute these client DLL's like dbcapi.dll, dblibXX.dll, etc. (so I can access third party servers like this)?  All the licenses I see in the SAP store sell some sort of server and I can't find a way to license the client so I can redistribute just these client DLL's (and not things like the Sybase Central GUI utility that also comes bundled with it).  Thanks much again.

**Comment by gperrow-SAP** [comment]
Sorry for the delay in responding, but I wanted to make sure I had the right information. To redistribute SAP software, you need to have an OEM license. If you have an OEM license, you can redistribute individual parts of the client software. 

If you don't already have an OEM license, email your contact information to me at graeme dot perrow at sap dot com and I can forward it to the sales team.

**Comment by dcsoft4** [comment]
Thank you so much Graeme, I have e-mailed the info and am closing this comment.
