### ISSUE TITLE
Failed to initalize dbcapi context, dbcapi version 2 required

### ISSUE THREAD

**Issue by rustyricky** [sqlanywhere/sqlanydb#18]
I'm having library issues with sqlanydb on CentOS 7.4.1708 running Python 2.7

What I've done:
- Installed SAP SQL Anywhere 17.0
- Created a simple test script:
```
#!/usr/bin/env python

import sqlanydb

conn = sqlanydb.connect(uid='', pwd='', host='***', ServerName='***')
```

The required *.so files could not be found after that, so I tried this (symlinks would've probably been the better choice here):
- Copied libraries from /opt/sqlanywhere17/lib32 to /usr/lib 
- Copied libraries from /opt/sqlanywhere17/lib64 to /usr/lib64

Now I receive the following exception:

```
Traceback (most recent call last):
  File "./anydb-test.py", line 5, in <module>
    conn = sqlanydb.connect(uid='', pwd='', host='***', ServerName='***')
  File "/usr/lib/python2.7/site-packages/sqlanydb.py", line 522, in connect
    return Connection(args, kwargs)
  File "/usr/lib/python2.7/site-packages/sqlanydb.py", line 538, in __init__
    parent = Connection.cls_parent = Root("PYTHON")
  File "/usr/lib/python2.7/site-packages/sqlanydb.py", line 478, in __init__
    API_VERSION_EX)
sqlanydb.InterfaceError: ('Failed to initalize dbcapi context, dbcapi version 2 required. Perhaps you are missing some sqlanywhere libaries?', 0)
```

The dbcapi lib was copied from /opt/sqlanywhere17/lib64, so it should be the correct version.
Any ideas?

**Comment by gperrow-SAP** [comment]
There are shell scripts in the bin64 directory that can be used to set up your environment. Run this command for a bash shell:

. /opt/sqlanywhere17/bin64/sa_config.sh

Note the "dot space" at the beginning. There is an equivalent sa_config.csh file there for C shell. Once you've done that, the python driver should be able to find everything it needs.

**Comment by rustyricky** [comment]
Awesome, that was it.
Thank you for this incredibly fast response!
