### ISSUE TITLE
Python 3 - Easy to fix Typo in README

### ISSUE THREAD

**Issue by alejandrovelez7** [sqlanywhere/sqlanydb#20]
In python 3 print became a function instead of statement, if you execute the `test_sqlany.py` example you get a compilation error ->

![image](https://user-images.githubusercontent.com/26886607/40991645-64cf6e48-68c2-11e8-92c3-d9150c484647.png)

If you just add a parenthesis to the example in this line then it compiles in python 3

`print("SQL Anywhere says: %s" % curs.fetchone())`

Want me to change it? Or add a note?

**Comment by gperrow-SAP** [comment]
I am fixing this now. Thanks for reporting it

**Comment by gperrow-SAP** [comment]
Fixed with version 1.0.10
