### ISSUE TITLE
Issue with prefetch 

### ISSUE THREAD

**Issue by aadant** [sqlanywhere/sqlanydb#6]
Looks like fetching large (>1000) result sets over the network is slow when latency is couple of microseconds. Maybe prefetching is disabled ? 

see 

http://sqlanywhere-forum.sap.com/questions/27823/why-is-python-sqlanydb-so-slow-when-fetching-resultsets-with-sap-iq-and-wan

**Comment by gperrow-SAP** [comment]
Looks like you answered your own question on the forum. Closing this issue.

**Comment by aadant** [comment]
In my opinion, there is still a bug there with IQ. It is not because the prefetch option is set to Conditional (the default in the manual) but not the default in practice that prefetching should not occur. It ruins performance over a WAN.

http://dcx.sybase.com/index.html#sa160/en/dbadmin/prefetch-option.html

Prefetching should be enabled by default as it is when connecting to the same database using JDBC.
